---
# hostinfo/handlers/main.yml: Handlers for hostinfo role

  - name: restart interfaces
    shell: 'ifdown {{ item.item.device }} && ifup {{ item.item.device }}'
    with_items: "{{ interface_name.content|b64decode }}"
